### ISSUE TITLE
Exception in test code during before_scenario causes exception in scenario.py

### ISSUE THREAD

**Issue by monicalicareti** [behave/behave#1179] opened 2024-06-12 08:29 UTC
Hi,

The test code I'm working on is doing some sanity checks of the test environment in the hook functions and I've run into a particular situation where an `AssertionError` raised in `before_scenario` caused behave to raise `Exception ValueError: Current _step is None` and terminate, without running any cleanup. 

This could be linked to #1003, but I'm not sure.
Unfortunately, I was unable reproduce this in a sandbox environment. It only happened in the "production" test code, which is running on a test bench with specific hardware. It is particularly disturbing in this context, because the abrupt termination can leave the test bench hardware in an uncertain state. 

Can you please give a hint into why this could be happening? 
Thank you!

**Comment by jenisys** [comment] 2024-06-13 17:55
Mmh, that is difficult as long as you cannot provide a minimal example how you use `behave`. 

* You need to provide more information
* `behave` does not just terminate your test run (only if your code raises a `SystemExit`, calls `sys.exit()` or is interrupted by the user which raises a `KeyboardInterrupt` exception)
* `behave` normally performs cleanups

VERSION/CONTEXT INFO:

* Which `behave` version are you using?
* What platform are you using (Windows, Linux, macOS, …) ?
* What Python version are you using ?

QUESTIONS:

* How have you registered your cleanups: By using a fixture or … ?
* Do you see a summary of the test run?
* What is shown after/when the `ValueError` is raised? (sanitized output should be sufficient; `behave` related details should be contained)
* Why do you think that no cleanups are performed?

NOTE:
The mentioned issue #1003 is completely different from what you experience. A `ValueError` exception is inherited from `Exception`.

SEE ALSO:
* [features/runner.context_cleanup.feature](https://github.com/behave/behave/blob/main/features/runner.context_cleanup.feature)
* [features/runner.hook_errors.feature](https://github.com/behave/behave/blob/main/features/runner.hook_errors.feature)

**Comment by jenisys** [comment] 2024-06-14 05:28
I also looked over the current implementation of `behave`:

* An `AssertionError`/`assert FAILED` can normally not cause an `ValueError` in `behave`
* I have no usages of `ValueError: Current _step` of parts of the error message in `behave`
* This may be caused by your code that uses `behave` (or an older version of `behave`)
* The chain of events: `AssertionError -> ValueError -> terminate/abort-program` should normally not occur

**Comment by monicalicareti** [comment] 2024-06-17 07:30
Hi jenisys,

Thank you for looking into this. 
I also did some more digging and it turns out that the error traces back to a custom formatter that we are using.
I still have to figure out how the formatter is called and why it crashes the test run.

**Comment by jenisys** [comment] 2024-06-27 17:30
Close this issue for now.

**Closed by jenisys** 2024-06-27 17:30 UTC
Labels: insufficient-information
