### ISSUE TITLE
Running behave from one drive on Windows where the featurs dir is on another file creates error

### ISSUE THREAD

**Issue by Moult** [behave/behave#902] opened 2021-02-04 21:14 UTC
Fully described in link below (note: BIMTester is just a light wrapper to Behave). Essentially a temp directory (but I guess it applies to regular directories too) contains the feature files in another drive, and this triggers and error.

https://github.com/IfcOpenShell/IfcOpenShell/issues/1294

A quick google turns up this: https://github.com/mesonbuild/meson/issues/2784 - perhaps a similar fix could be applied?

**Comment by aothms** [comment] 2021-02-05 09:03
This is caused by the fix for #80, which uses a relative path, which indeed does not always work on Windows which does not have a single shared root for the drives. The meson guys indeed implemented a workaround to fallback to absolute path https://github.com/mesonbuild/meson/commit/f00e2ef96b4ddf082100ea9a60b680658a570456

**Comment by rbertucat** [comment] 2021-02-09 10:14
I've tried locally to apply the workaround suggested by @aothms, and that worked great.

Note that it also must be applied to that file: https://github.com/behave/behave/blob/994dbfe30e2a372182ea613333e06f069ab97d4b/behave/model_core.py#L271

I'll do a PR when I get a chance.

**Comment by jenisys** [comment] 2022-01-09 11:42
Will be addressed in: #990

**Closed by jenisys** 2022-01-09 11:42 UTC
Labels: duplicated, wontfix
