### ISSUE TITLE
UnicodeEncodeError when having utf-8 characters in feature

### ISSUE THREAD

**Issue by ignatenkobrain** [behave/behave#487] opened 2016-08-23 12:20 UTC
```python
Traceback (most recent call last):
  File "/usr/bin/behave-2", line 9, in <module>
    load_entry_point('behave==1.2.5', 'console_scripts', 'behave')()
  File "/usr/lib/python2.7/site-packages/behave/__main__.py", line 111, in main
    print(u"ParseError: %s" % e)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 92-103: ordinal not in range(128)
```

for better visibility I tried to use ZBSP (zero-width space) in multiline text (I'm comparing 80-characters text and it's not nice with steps.). I tried to add ZBSPs in multiline text to tell behave that I have spaces, but I don't want to see them in text editor).

**Comment by jenisys** [comment] 2016-09-14 20:31
The problem is probably introduced by your own source code.
Generally, it often helps to provide an encoding hint in the python code (otherwise encoding=ascii is assumed in Python2):

```python
# -*- coding: UTF-8 -*-
# FILE: features/steps/my_steps.py
...
```

In addition, ensure that you use unicode strings with special unicode characters.

**Comment by jenisys** [comment] 2016-10-01 17:26
Looking at your traceback again:
You had an ParserError in your feature file. Feature file must have an UTF-8 encoding.
The weird thing, "parser.py" does not show up in your traceback.

Could you provide an example of your feature file ?

**Comment by jenisys** [comment] 2016-10-15 11:51
No feedback or response.
Close it.

**Closed by jenisys** 2016-10-15 11:51 UTC
Labels: unicode
