### ISSUE TITLE
JUnit XML output is not well-formed

### ISSUE THREAD

**Issue by fhars** [behave/behave#510] opened 2016-11-23 08:15 UTC
The JUnit XML output logic just puts all log output into a CDATA section without handling characters that are illegal in XML (like control characters), This will for example happen if the log output happess to be the log of a pexpect session controlling an interactive application with keyboard shoutcuts.

**Comment by jenisys** [comment] 2016-11-23 21:53
That what CDATA is for (IMHO). Special characters do not need to be escaped in CDATA sections (in except one case). You can easily check the output with ``xmllint`` and it will not complain.

```bash
# USING JUNIT OUTPUT FROM: behave --junit features/
$ xmllint --schema etc/junit.xml/behave_junit.xsd reports/TESTS-*.xml && echo OK
...
reports/TESTS-userdata.xml validates
OK

# ALTERNATIVE:
$ xmllint --schema etc/junit.xml/behave_junit.xsd reports/TESTS-*.xml | grep "parser error"
reports/TESTS-background.xml validates
reports/TESTS-capture_stderr.xml validates
...
reports/TESTS-tags.tag_expression.xml validates
reports/TESTS-tags.xml validates
reports/TESTS-userdata.xml validates
```

Can you explain why you think that the XML output is not valid ?
* Refer to an XML specification section that indicates what is wrong
* Provide example output and how it should look like (in your opinion)
* Provide a XML checker that complains about the checked XML

**Comment by fhars** [comment] 2016-11-24 10:31
I think the XML output is invalid as the XML specification explicitly says that documents containing illegal characters are not well formed,

The normative reference is XML 1.0 (Fifth Edition), section 2.2 https://www.w3.org/TR/REC-xml/#charsets
although XML 1.1 section 2.1 spells it out more explicitly.

Any compliant parser and checker will flag this, I have seen this with the parser used by Jenkins' Junit import feature, the xml display logic in firefox and xmllint.

I'd suggest to replace control characters in the <system-out> elements with their conventional ascii representation "^C", "^D" etc.

````
$ cat ctrl.feature 
Feature: An illegal char
  Scenario: Control-D
    When we print ^D
$ cat steps/steps.py

@when(u'we print ^D')
def step_impl(context):
    print("\04")
$ behave --junit ctrl.feature 
Feature: An illegal char # ctrl.feature:1

  Scenario: Control-D  # ctrl.feature:2
    When we print ^D   # steps/steps.py:2 0.000s

1 feature passed, 0 failed, 0 skipped
1 scenario passed, 0 failed, 0 skipped
1 step passed, 0 failed, 0 skipped, 0 undefined
Took 0m0.000s
$ xmllint `find . -name TESTS-*`
./reports/TESTS-ctrl.xml:12: parser error : CData section not finished

@scenario.begin
  Scenario: Control-D
    When we

^
./reports/TESTS-ctrl.xml:12: parser error : PCDATA invalid Char value 4

^
./reports/TESTS-ctrl.xml:14: parser error : Sequence ']]>' not allowed in content

 ^
./reports/TESTS-ctrl.xml:14: parser error : Sequence ']]>' not allowed in content
]]>
^
./reports/TESTS-ctrl.xml:14: parser error : internal error: detected an error in element content

]]>
^
$ 
```

**Comment by jenisys** [comment] 2016-11-24 21:18
I will look into it.

COMMENTS:
* The XML contains unicode (normally UTF-8), not ASCII.
* Currently, I am more inclined to strip any chars that are outside the Unicode charset specification (mentioned above).

**Comment by bgura** [comment] 2016-12-29 17:14
@jenisys i'm running into this issue as well. Specifically...

I have a python file which is giving a rutime warning on stderr. This is getting dumped into CDATA for captured stderr. The problem is, the warning prints the path which has '\a' in it which gets turned into the "BEL" control character.

As an example if I had the following error generated on stderr, all the "\a" would be replaced with the "[BEL]" control character causing the CDATA to be malformed.

`c:\apples-behave\apples_behave\apples\file.py:68: RuntimeWarning: Writing negative value into unsigned field`

**Comment by dhallam** [comment] 2017-01-17 06:28
Another scenario to add that is failing as well: embedded CDATA in system-out, e.g. 

```
<system-out>
<![CDATA[
@scenario.begin
  Scenario: test stuff
    To test stuff

@scenario.end
--------------------------------------------------------------------------------

Captured stdout:
Did some stuff - generated the following response:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Response>
    <ResponseData><![CDATA[random < things that we want to > escape]]></ResponseData>
</Response>
]]>
</system-out>
```

The closing `]]>` after the word escape closes the CDATA section started just after `<system-out>` and the resulting document is invalid.

One potential solution to this issue might be something similar to http://stackoverflow.com/questions/12860754/using-cdata-inside-another-cdata

Added to this issue as the `]]>` are special characters in this context and should be considered as part of the overall solution, but if a separate issue should be raised, let me know.

**Comment by jenisys** [comment] 2018-02-15 22:26
false

**Comment by novel** [comment] 2018-07-05 08:31
This is still actual. CDATA section might contain invalid XML that results in issues with Jenkins for example:

```
org.dom4j.DocumentException: Error on line 2387 of document  : An invalid XML character (Unicode: 0x0) was found in the CDATA section. Nested exception: An invalid XML character (Unicode: 0x0) was found in the CDATA section.
```
`xmllint` output:

```
test.xml:3589: parser error : Char 0x0 out of allowed range
test.xml:3589: parser error : CData section not finished

Failing step: snipped 
test.xml:3589: parser error : Premature end of data in tag error line 2
test.xml:3589: parser error : Premature end of data in tag testcase line 2
test.xml:3589: parser error : Premature end of data in tag testsuite line 2
```

**Comment by sjlawson** [comment] 2018-11-28 04:02
If you want more control over what goes into the CDATA section, here is a solution:
Copy junit.py from env/lib/python3.6/site-packages/behave/reporter/junit.py to a directory you will maintain as a custom reporter. I put mine in a folder called `reporters`

(the above path assumes you have a virtualenv called 'env' and you are using python3.6 -- adjust based on your environment)

In that file, find the method, `def CDATA(text=None):`
modify the `text` variable as you wish - apply filters or just set `text = ''` if you don't need it. 

Then in your environments.py, add this to the imports area:
`from reporters.junit import JUnitReporter`

Finally, in the `before_all(context)` method, add this:  
```
    junit_reporter = JUnitReporter(context.config)
    context.config.reporters.append(junit_reporter)
```

Now you have your very own custom JUnit xml report generator!

**Comment by jenisys** [comment] 2019-06-23 16:36
Reopen.

**Comment by nc-tongh** [comment] 2019-12-31 04:56
Reopen.

**Comment by nc-tongh** [comment] 2019-12-31 04:58
Sorry for reopening this but I'm getting confusing about the status. 
Is the last commit from @kwargs fixing the issue?

**Comment by venkatrao59** [comment] 2020-06-24 04:58
@kwargs do you have any plans to merge commit https://github.com/kwargs/behave/commit/e6d7226f2ecd103afd3bc477c96462c19756ca26 into master??

**Comment by kwargs** [comment] 2020-06-28 18:44
@venkatrao59  I'm not the maintainer here.

**Comment by rodicaDan** [comment] 2020-08-05 14:05
Using behave 1.2.6 and 1.2.7dev1 and python 3.7 or 3.8.5:
When the junit report is generated it cannot be read by jenkins.
Error:

An invalid XML character (Unicode: 0x1b) was found in the CDATA section.
--
Can anyone please help with a workaround as I need these reports in jenkins.

**Comment by kwargs** [comment] 2020-08-05 18:59
@rodicaDan: you can try this https://github.com/behave/behave/pull/787 patch.
It should help.

**Comment by ncoghlan** [comment] 2020-11-02 02:29
I hit this as well (due to ANSI color control codes in the captured stdout data).

The #787 patch looked good to me, but I haven't actually tried it out (we're going to work around this in the near term by filtering the output of the offending commands in our test suite, rather than by fixing the general case at the behave level).

**Comment by fhars** [comment] 2021-08-10 14:47
Stale bot is a bit eager here, right?

**Closed** 2022-10-23 13:00 UTC
Labels: minor
