### ISSUE TITLE
Question: Behave 1.2.7 (it has breaking changes)

### ISSUE THREAD

**Issue by Mulugruntz** [behave/behave#1044] opened 2022-07-21 13:51 UTC
Hi,

I noticed that some features will be integrated into 1.2.7 (I saw that https://github.com/behave/behave/pull/967 ).
Then, I noticed that 1.2.7 was in development for over 4 years now.

Also, I see that we use some subset of semver with major/minor/patch.
https://github.com/behave/behave/blob/b12a6ebcc52e1db4fa5d09620d5be27e0cec509e/.bumpversion.cfg#L4

Last but not least, the [changelog](https://github.com/behave/behave/blob/b12a6ebcc52e1db4fa5d09620d5be27e0cec509e/CHANGES.rst#version-127-unreleased) mentions several breaking changes.

For all the users that rely on behave to use a semver, a potential 1.2.7 (patch bump) should not have breaking changes.

From what I see from the changelog, it should either be 1.3.0 or 2.0.0 (because of the breaking changes, it should be 2.0.0). This way, people using automated tools will detect this as a major version upgrade (including breaking changes) and their CICD pipeline will not break.

That being said, what is needed to have this new release and also smaller but more regular releases?

**Comment by bittner** [comment] 2022-07-24 13:08
Duplicate of #855.

Behave doesn't follow semver (yet), despite the `.bumpversion.cfg` file. I fully agree that 1.3.0 or 2.0.0 would be good version numbers for an upcoming release, mostly because nowadays developers simply assume that a project with a version triple applies semver.

@jenisys, maybe 1.3.0 could be the last release to support Python 2.7 (and some older versions of Python 3), and 2.0.0 could finally drop Python 2.7 and clean up some of the code base's legacy. What are your plans?

**Closed by bittner** 2022-07-24 13:08 UTC
Labels: duplicated, question

**Comment by bittner** [comment] 2022-07-24 13:19
Related:

- #1028
- #1029
- #1030
