### ISSUE TITLE
AmbiguousStep definition

### ISSUE THREAD

**Issue by tacmanvsa** [behave/behave#978] opened 2021-12-06 11:16 UTC
Hi,

Using behave 1.2.6. Getting an **AmbiguousStep** exception on the following 2 steps.

`@when('go to the create new user page')`

`@when('go to the login page')`

I'm missing the point here:
- why are these 2 steps ambigious?
- what is the default step matching strategy?
- how to fix it?

Thanks

**Comment by jenisys** [comment] 2021-12-06 12:21
I assume that the steps in your scenario / feature file look like that.
But your step implementation patterns probably use a parameter / placeholder, like:

```python
# — FILE: features/steps/example_steps.py
from behave import when

@when(u‘go to the {page_name}‘)
def step_go_to_page(ctx, page_name):
    pass

@when(u‘go to the create {page_name}‘)
def step_go_to_create_page(ctx, page_name):
    pass
```

HINTS:
* Ordering of steps matters (longest prefix first; regular expressions are greedy and match as much as possible)
* Use double-quotes for parameters / placeholders
* Use typed parameter (like: number, word, …) instead of untyped parameter that use match-anything pattern “.*“

BETTER (ordering matters, longest prefix first):

```python
# — FILE: features/steps/example_steps2.py
from behave import when

@when(u‘go to the “create {page_name}“‘)
def step_go_to_create_page(ctx, page_name):
    pass

@when(u‘go to the “{page_name}“‘)
def step_go_to_page(ctx, page_name):
    pass
```

**Comment by jenisys** [comment] 2021-12-06 12:23
HINT: The exception indicates where the problem is (see: trace-back)

**Comment by jenisys** [comment] 2021-12-07 22:08
@tacmanvsa Issue resolved?

**Comment by jenisys** [comment] 2021-12-12 11:33
NO REACTION: Therefore, everything is probably clear or resolved.
=> CLOSE IT.

**Closed by jenisys** 2021-12-12 11:33 UTC
Labels: question
